# Generated by Django 2.1.5 on 2019-02-07 07:00

from django.db import migrations, models
import django.utils.timezone
import tutorials.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20190206_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=tutorials.models.generate_filename_cat, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=500, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
